const ASSET = 'assets/illustrations/';
const topics = [
 {id:'letters', title:'Harflar', icon:'assets/icons/harflar.png', cls:'c0', items:[
 ['a.jpg','A'],['b.jpg','B'],['d.jpg','D'],['e.jpg','E'],['f.jpg','F'],['g.jpg','G'],['g‘.jpg','G‘'],['h.jpg','H'],['i1.jpg','I'],['j.jpg','J'],['k.jpg','K'],['l.jpg','L'],['m.jpg','M'],['n.jpg','N'],['ng.jpg','Ng'],['o.jpg','O'],['o‘.jpg','O‘'],['p.jpg','P'],['q.jpg','Q'],['r.jpg','R'],['s.jpg','S'],['sh.jpg','Sh'],['t.jpg','T'],['u.jpg','U'],['v.jpg','V'],['x.jpg','X'],['y.jpg','Y'],['z.jpg','Z'],['ch.jpg','Ch']
 ]},
 {id:'numbers', title:'Sonlar', icon:'assets/icons/sonlar.png', cls:'c1', items:[1,2,3,4,5,6,7,8,9,10].map(n=>[`${n}.jpg`,String(n)])},
 {id:'colors', title:'Ranglar', icon:'assets/icons/ranglar.png', cls:'c2', items:[['qizil.jpg','Qizil'],['sariq.jpg','Sariq'],['yashil.jpg','Yashil'],['ko‘k.jpg','Ko‘k'],['qora.jpg','Qora'],['oq.jpg','Oq'],['pushti.jpg','Pushti'],['binafsha.jpg','Binafsha'],['jigarrang.jpg','Jigarrang'],['havorang.jpg','Havorang'],['osmonrang.jpg','Osmonrang'],['zangori.jpg','Zangori'],['turkuazrang.jpg','Turkuazrang'],['Kulrang.jpg','Kulrang'],['Bejrang .jpg','Bejrang'],['koralrang.jpg','Koralrang'],['oltinrang.jpg','Oltinrang'],['kumushrang.jpg','Kumushrang'],['to‘q sarie.jpg','To‘q sariq'],['to‘qkok.jpg','To‘q ko‘k']]},
 {id:'fruits', title:'Mevalar', icon:'assets/icons/mevalar .png', cls:'c3', items:[['anor.jpg','Anor'],['apilsin.jpg','Apelsin'],['banan.jpg','Banan'],['behi.jpg','Behi'],['kivi.jpg','Kivi'],['limon.jpg','Limon'],['nok.jpg','Nok'],['olcha.jpg','Olcha'],['olma.jpg','Olma'],['O‘rik.jpg','O‘rik'],['olxo‘ri.jpg','Olxo‘ri'],['qovun.jpg','Qovun'],['qulupnay.jpg','Qulupnay'],['tarvuz.jpg','Tarvuz'],['uzum.jpg','Uzum'],['xurmo.jpg','Xurmo'],['ananas.jpg','Ananas']]},
 {id:'body', title:'Tana a’zolari', icon:'assets/icons/tana azolar.png', cls:'c4', items:[['Bosh.jpg','Bosh'],['Burun.jpg','Burun'],['Ko‘z.jpg','Ko‘z'],['Og‘iz.jpg','Og‘iz'],['Oyoq.jpg','Oyoq'],['Qo‘l.jpg','Qo‘l'],['Quloq.jpg','Quloq']]},
 {id:'shapes', title:'Shakllar', icon:'assets/icons/shakllar.png', cls:'c5', items:[['Doira.jpg','Doira'],['Kvadrat.jpg','Kvadrat'],['Oval.jpg','Oval'],["To'rtburchak.jpg",'To‘rtburchak'],['Uchburchak.jpg','Uchburchak'],['Yulduz.jpg','Yulduz']]},
 {id:'nature', title:'Tabiat', icon:'assets/icons/tabiat.png', cls:'c6', items:[['Ormon.jpg','O‘rmon'],['Oyva yulduzlar.jpg','Oy va yulduzlar'],['bulut.jpg','Bulut'],['daraxt.jpg','Daraxt'],['daryo.jpg','Daryo'],['dengiz.jpg','Dengiz'],['gul.jpg','Gul'],['kamalak.jpg','Kamalak'],['o‘tloq.jpg','O‘tloq'],['olov.jpg','Olov'],['qor.jpg','Qor'],['quyosh.jpg','Quyosh'],['shamol.jpg','Shamol'],['tog‘.jpg','Tog‘'],['yomgir.jpg','Yomg‘ir']]},
 {id:'time', title:'Vaqt', icon:'assets/icons/vaqt.png', cls:'c7', items:[['soat.jpg','Soat'],['soat1.jpg','Soat'],['chizma soat.jpg','Chizma soat'],['kalendar.jpg','Kalendar'],['kun va tun.jpg','Kun va tun'],['qum soat.jpg','Qum soat'],['sana.jpg','Sana'],['sekundomer.jpg','Sekundomer']]},
 {id:'transport', title:'Transport', icon:'assets/icons/transport.png', cls:'c8', items:[['avtobus.jpg','Avtobus'],['avtomobil.jpg','Avtomobil'],['havoshari.jpg','Havo shari'],['kema.jpg','Kema'],['mototsikl.jpg','Mototsikl'],['politsiyamashinasi.jpg','Politsiya mashinasi'],['poyezd.jpg','Poyezd'],['samalyot.jpg','Samolyot'],['samasval.jpg','Samosval'],['tezyordam.jpg','Tez yordam'],['traktor.jpg','Traktor'],['velosiped.jpg','Velosiped'],['vertalyot.jpg','Vertolyot'],['yaxta.jpg','Yaxta'],['yonginmashinasi.jpg','Yong‘in mashinasi']]}
];
const app=document.getElementById('app'); let current={page:'home',topic:null,index:0}; let deferredPrompt=null; let soundOn=localStorage.getItem('soundOn')!=='0';
const $=s=>document.querySelector(s); const esc=s=>String(s).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
function path(t,item){return ASSET+encodeURIComponent(t.id)+'/'+encodeURIComponent(item[0]).replace(/%2F/g,'/');}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show-toast');setTimeout(()=>t.classList.remove('show-toast'),2600)}
function setNav(p){document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===p))}
function speak(text){if(!soundOn||!('speechSynthesis'in window))return; speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(text);u.lang='uz-UZ';u.rate=.82;speechSynthesis.speak(u)}
function renderHome(){current.page='home';setNav('home');app.innerHTML=`<section class="hero"><div><div class="eyebrow">KICHKINTOYLAR UCHUN TA’LIM</div><h2>O‘ynab<br><span>o‘rganamiz!</span></h2><p>Rasmlarni ko‘ring, nomini eshiting va bilimlaringizni sinang.</p><button class="btn" id="startLessons">Darslarni boshlash ✨</button></div><img src="assets/icons/logo.png" alt="Bolajonlar logosi"></section><div class="section-title"><small>9 TA QIZIQARLI MAVZU</small><h2>Darslar</h2></div><section class="lessons-grid" id="homeLessons"></section><div class="install-wrap"><button class="install-btn" id="installBtn">📲 Telefonga o‘rnatish</button><div class="install-note" id="installNote">Ilovani telefoningizga alohida ilova sifatida o‘rnating.</div></div>`; renderTopicCards('#homeLessons'); $('#startLessons').onclick=renderLessons; $('#installBtn').onclick=installApp;}
function renderTopicCards(sel){const box=$(sel);box.innerHTML=topics.map((t,i)=>`<button class="card ${t.cls}" data-topic="${t.id}"><img src="${t.icon}" alt="${t.title}"><h3>${t.title}</h3><p>${t.items.length} ta rasm</p></button>`).join('');box.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>openTopic(b.dataset.topic,0));}
function renderLessons(){current.page='lessons';setNav('lessons');app.innerHTML=`<div class="section-title"><small>RANGLI DARS KARTOCHKALARI</small><h2>📚 Darslar</h2><p>O‘zingizga yoqqan mavzuni tanlang.</p></div><section class="lessons-grid" id="lessonGrid"></section>`;renderTopicCards('#lessonGrid');}
function openTopic(id,index=0){const t=topics.find(x=>x.id===id);if(!t)return;current={page:'study',topic:id,index:Math.max(0,Math.min(index,t.items.length-1))};setNav('lessons');renderStudy();}
function renderStudy(){const t=topics.find(x=>x.id===current.topic),it=t.items[current.index],pct=((current.index+1)/t.items.length)*100;app.innerHTML=`<div class="lesson-top"><div class="lesson-nav"><button class="btn secondary" id="backHome">🏠 Bosh sahifa</button><button class="btn secondary" id="backLessons">← Barcha mavzular</button></div><strong>${current.index+1} / ${t.items.length}</strong></div><div class="section-title"><small>MAVZU</small><h2>${t.title}</h2><p>Rasmga qarang va nomini ovozda eshiting 🔊</p></div><div class="progress"><div style="width:${pct}%"></div></div><section class="study-card"><img id="lessonImg" src="${path(t,it)}" alt="${it[1]}"><h2>${esc(it[1])}</h2><button class="btn" id="listenOne">🔊 Eshitish</button><div class="lesson-actions"><button class="btn secondary" id="prev" ${current.index===0?'disabled':''}>← Oldingi</button><button class="btn" id="next">${current.index===t.items.length-1?'Tugatish':'Keyingi →'}</button></div></section>`;$('#backHome').onclick=renderHome;$('#backLessons').onclick=renderLessons;$('#listenOne').onclick=()=>speak(it[1]);$('#prev').onclick=()=>{if(current.index>0){current.index--;renderStudy()}};$('#next').onclick=()=>{if(current.index<t.items.length-1){current.index++;renderStudy()}else renderLessons()};$('#lessonImg').onerror=()=>toast('Bu rasm fayli topilmadi: '+it[0]);}
function renderQuiz(){current.page='quiz';setNav('quiz');app.innerHTML=`<section class="quiz-box"><button class="btn secondary page-back" id="quizHome">🏠 Bosh sahifa</button><div class="section-title"><small>10 TA SAVOL</small><h2>🧩 Quiz Challenge</h2><p>Natijangiz Reyting bo‘limida saqlanadi.</p></div><label for="playerName"><b>Ismingizni yozing:</b></label><input class="name-input" id="playerName" maxlength="30" placeholder="Masalan: Muhammad"><button class="btn" id="beginQuiz">Quizni boshlash →</button></section>`;$('#quizHome').onclick=renderHome;$('#beginQuiz').onclick=()=>{const name=$('#playerName').value.trim();if(!name)return toast('Iltimos, ismingizni yozing');startQuiz(name)}}
function sampleQuiz(){const pool=topics.flatMap(t=>t.items.map(it=>({t,it})));for(let i=pool.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]]}return pool.slice(0,10)}
function startQuiz(name){const qs=sampleQuiz();let qi=0,score=0;function show(){const q=qs[qi];const opts=[q,...sampleQuiz().filter(x=>x.it[1]!==q.it[1]).slice(0,3)];for(let i=opts.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[opts[i],opts[j]]=[opts[j],opts[i]]}app.innerHTML=`<section class="quiz-box"><div class="lesson-top"><button class="btn secondary page-back" id="questionHome">🏠 Bosh sahifa</button><strong>Savol ${qi+1} / 10</strong><strong>⭐ ${score}</strong></div><div class="progress"><div style="width:${(qi/10)*100}%"></div></div><h2>${qi+1}-savol</h2><p>Rasmda nima tasvirlangan?</p><img class="question-image" src="${path(q.t,q.it)}" alt="Savol rasmi"><div class="answers">${opts.map(o=>`<button class="answer" data-a="${esc(o.it[1])}">${esc(o.it[1])}</button>`).join('')}</div></section>`;$('#questionHome').onclick=renderHome;document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>{const ok=b.dataset.a===q.it[1];b.classList.add(ok?'correct':'wrong');if(ok){score++;speak('To‘g‘ri!')}else speak('Yana urinib ko‘ring');document.querySelectorAll('.answer').forEach(x=>x.disabled=true);setTimeout(()=>{qi++;qi<10?show():finishQuiz(name,score)},650)})}show()}
function prize(score){if(score<=2)return ['🌟','Yulduzcha','Harakat qilganingiz uchun yulduzcha!'];if(score<=4)return ['🎈','Sharlar','Rangli sharlar sovrini!'];if(score===5)return ['🚗','Mashina','Siz mashina yutdingiz!'];if(score===6)return ['🎁','Sovg‘a','Siz sovg‘a yutdingiz!'];if(score===7)return ['🏅','Medal','Siz medal yutdingiz!'];if(score===8)return ['🧸','O‘yinchoq','Ajoyib o‘yinchoq sizniki!'];if(score===9)return ['🏆','Kubok','Siz kubok yutdingiz!'];return ['👑','Super chempion','Eng katta sovrin sizniki!']}
function finishQuiz(name,score){const p=prize(score),rows=JSON.parse(localStorage.getItem('bolajonlarRanking')||'[]');rows.push({name,score,emoji:p[0],prize:p[1],date:Date.now()});rows.sort((a,b)=>b.score-a.score||b.date-a.date);localStorage.setItem('bolajonlarRanking',JSON.stringify(rows.slice(0,50)));app.innerHTML=`<section class="quiz-box result"><button class="btn secondary page-back" id="resultHome">🏠 Bosh sahifa</button><div class="prize">${p[0]}</div><h2>${esc(name)}, tabriklaymiz! 🎉</h2><p><b>${score} ball</b> oldingiz.</p><h3>${p[1]}</h3><p>${p[2]}</p><button class="btn" id="toRanking">🏆 Reytingni ko‘rish</button><button class="btn secondary" id="again">Yana o‘ynash</button></section>`;$('#resultHome').onclick=renderHome;$('#toRanking').onclick=renderRanking;$('#again').onclick=renderQuiz}
function renderRanking(){current.page='ranking';setNav('ranking');const rows=JSON.parse(localStorage.getItem('bolajonlarRanking')||'[]');app.innerHTML=`<section class="ranking-box"><button class="btn secondary page-back" id="rankingHome">🏠 Bosh sahifa</button><div class="section-title"><small>ENG YAXSHI NATIJALAR</small><h2>🏆 Reyting</h2><p>Ism, ball va yutilgan sovrinlar.</p></div><div class="ranking-list">${rows.length?rows.map((r,i)=>`<div class="rank-item"><div class="rank-left"><span class="rank-medal">${i===0?'🥇':i===1?'🥈':i===2?'🥉':'⭐'}</span><div><b>${esc(r.name)}</b><div>${r.score} ball</div></div></div><div>${r.emoji} ${r.prize}</div></div>`).join(''):'<div class="empty">Hali natijalar yo‘q. Quizni ishlab ko‘ring! 😊</div>'}</div></section>`;$('#rankingHome').onclick=renderHome}
async function installApp(){if(deferredPrompt){deferredPrompt.prompt();const {outcome}=await deferredPrompt.userChoice;if(outcome==='accepted')toast('O‘rnatish qabul qilindi');deferredPrompt=null;return}const isiOS=/iphone|ipad|ipod/i.test(navigator.userAgent);toast(isiOS?'Safari menyusidan “Bosh ekranga qo‘shish”ni tanlang.':'Brauzer menyusidan “Ilovani o‘rnatish” yoki “Bosh ekranga qo‘shish”ni tanlang.');}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;});window.addEventListener('appinstalled',()=>toast('Bolajonlar muvaffaqiyatli o‘rnatildi! 🎉'));
document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>({home:renderHome,lessons:renderLessons,quiz:renderQuiz,ranking:renderRanking}[b.dataset.nav]()));$('#soundToggle').onclick=()=>{soundOn=!soundOn;localStorage.setItem('soundOn',soundOn?'1':'0');$('#soundToggle').textContent=soundOn?'🔊':'🔇';if(soundOn)speak('Ovoz yoqildi')};$('#soundToggle').textContent=soundOn?'🔊':'🔇';if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js').catch(()=>{}));renderHome();
